# Site settings
title: RESx
description: >
  Learning Resources of Faculty of Computer and
  Information Sciences at Ain Shams University.
repo_url: https://github.com/RESx/RESx.github.io/

# Author Info
author:
  name: RESx
  email:
  github: https://github.com/RESx/

# Build settings
markdown: kramdown

# Enable Pagination
paginate: 2
paginate_path: "/news/page-:num/"


# Collections declaration
collections:

  courses:
    output: true
    permalink: /courses/:name
    
  courses-categories:
    output: true
    permalink: /courses/:name


# Default values for collections
defaults:

  - scope:
      path: ""
      type: "courses"
    values:
      layout: "course"

  - scope:
      path: ""
      type: "courses-categories"
    values:
      layout: "category"
      style: "info"