# Site settings
title: RESx
description: >
  Learning Resources of Faculty of Computer and
  Information Sciences at Ain Shams University.

# Author Info
author:
  name: RESx
  email:
  github: https://github.com/RESx

# Build settings
markdown: kramdown

# Enable Pagination
paginate: 2
paginate_path: "/news/page-:num/"


# Collections declaration
collections:

  courses:
    output: true
    permalink: /courses/:name
    
  courses-categories:
    output: true
    permalink: /courses/:name

  sponsors:
    output: true

  team:
    output: true


# Default values for collections
defaults:

  - scope:
      path: ""
      type: "courses"
    values:
      layout: "course"

  - scope:
      path: ""
      type: "courses-categories"
    values:
      layout: "category"
      style: "info"

  - scope:
      path: ""
      type: "team"
    values:
      layout: "member"