# Site settings
title: RESx
description: >
  Learning Resources of Faculty of Computer and
  Information Sciences at Ain Shams University.

# Author Info
author:
  name: RESx
  email:
  github: https://github.com/FCIS-ASU-RESx

# Build settings
markdown: kramdown

collections:

  courses:
    output: true
    permalink: /courses/:name
    
  sponsors:
    output: true